name = "cf-hl-alerts"
main = "src/index.ts"
compatibility_date = "2025-09-04"

kv_namespaces = [
  { binding = "HL_ALERT_STATE", id = "3f334020c16e4aee8c0f4bd5ead308f3" }
]

[triggers]
# minute poll + daily at 02:00 UTC (09:00 Bangkok) + 14:00 UTC (21:00 Bangkok)
crons = ["*/1 * * * *", "0 2 * * *", "0 14 * * *"]

[vars]
POLL_CRON   = "*/1 * * * *"
DAILY_CRON  = "0 2 * * *"    # 09:00 Bangkok
DAILY_CRON_2 = "0 14 * * *"  # 21:00 Bangkok
