name = "hl-alerts"
main = "src/index.ts"
compatibility_date = "2025-09-02"

kv_namespaces = [
  { binding = "HL_ALERT_STATE", id = "3f334020c16e4aee8c0f4bd5ead308f3" }
]

[triggers]
# minute poll AND daily report at 02:00 UTC (= 09:00 Bangkok)
crons = ["*/1 * * * *", "0 2 * * *"]

[vars]
POLL_CRON = "*/1 * * * *"
DAILY_CRON = "0 2 * * *"
